name: Rust

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Update
        run: rustup update
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        env:
          ETHSCAN: ${{ secrets.ETHSCAN }}
        run: cargo test --verbose
